<template>
    <section class="w-full max-w-[64.8125rem] mx-auto  pt-10 pb-10">
        <article class=" w-full flex flex-col items-center space-y-8">
           <div class=" w-full flex flex-col items-center space-y-4">
               <h1 class=" text-black font-Inter text-[2rem] sm:text-[2.5rem] font-normal">Free AI Image Generator from Text</h1>
                <p class=" text-black font-Inter text-xl font-normal max-w-[59.0925rem]">
                    Discover the creative possibilities with our Text-to-Image AI Generator. Transform your ideas into visual art with just a few clicks. Enter your text, select a style, choose the shape of your image, and set the number of results you wish to see. Our AI will craft an image that aligns with your description.
                    Text-to-Image.ai is an innovative platform that brings your words to life. Whether you're imagining a surreal landscape, a detailed character sketch, or a unique abstract design, our tool generates high-quality images in seconds. Simply type in your description, pick your preferred art style, define the shape, and decide how many variations you want. The AI does the rest.
                    Our Text-to-Image AI is accessible through any web browser and supports all devices (PC, Mac, Android, iOS) without the need for additional software. This powerful tool is perfect for artists, designers, content creators, or anyone looking to bring their imaginative concepts to visual reality.
                </p>
           </div>
              <div class=" w-full flex flex-col items-center space-y-6">
               <h1 class=" text-black font-Inter text-[2rem] sm:text-[2.5rem] font-normal">Why should you use Text-to-Image AI Generator?</h1>
                <div class=" text-black font-Inter text-xl font-normal max-w-[59.0925rem]">
                    <p>
                        The Text-to-Image AI Generator opens up a new realm of digital art creation. It’s an excellent tool for artists exploring new styles, marketers creating engaging visuals, and writers visualizing scenes or characters. Plus, it’s incredibly user-friendly and efficient.
                       <br> Features of Text-to-Image AI Generator:
                    </p>
                    <ul class=" pl-8 list-disc">
                        <li>
                            Customizable Text Input: Describe what you want in detail, and our AI will interpret your words into images.
                        </li>
                        <li>
                             Multiple Art Styles: Choose from a variety of art styles like Painted Anime, Digital Painting, Vintage Comic, Watercolor, and more.
                        </li>
                        <li>
                            Shape Selection: Specify the shape of your image - whether it's a wide landscape, a tall portrait, or a standard square.
                        </li>
                        <li>
                              Quantity Control: Decide how many image results you want from a single prompt, giving you multiple visual interpretations of your text.
                        </li>
                        <li>
                            High-Quality Images: Enjoy high-resolution images generated by our advanced AI, retaining the quality and essence of your original idea.
                        </li>
                    </ul>
                    
                    <p>
                        How to generate images from text? Step 1: Visit Text-to-Image.ai on your device.
                    Step 2: Enter your descriptive text in the input box.
                    Step 3: Choose your desired art style, shape, and quantity of results.
                    Step 4: Click the "Generate" button.
                    Step 5: View the AI-generated images based on your description. Select and download your favorites directly to your device.
                    With Text-to-Image.ai, you can turn any textual concept into stunning visual art. We continuously update our AI to provide the best and most innovative experience. Share this tool with friends and family, and start creating today!
                    Our tool respects the creative process and is designed for ethical use. Please refer to our Terms of Service for more details.
                    </p>
                </div>
           </div>
        </article>
    </section>
</template>