<template>
    <section class="w-full max-w-[64.8125rem] mx-auto  pt-10 pb-10">
        <article class=" w-full flex flex-col items-center space-y-8">
           <div class=" w-full flex flex-col items-center space-y-4">
               <h1 class=" text-black font-Inter text-[2rem] sm:text-[2.5rem] font-normal">Generador Gratuito de Imágenes AI a partir de Texto</h1>
                <p class=" text-black font-Inter text-xl font-normal max-w-[59.0925rem]">
                    Descubre las posibilidades creativas con nuestra red neuronal que crea imágenes a partir de textos. Transforma tus ideas en arte visual con solo unos pocos clics. Introduce tu texto, selecciona un estilo, define la forma de la imagen y el número de resultados que deseas ver. Generator AI creará una obra de arte que coincida con tu descripción. Art-Generator.ai es una plataforma innovadora que da vida a tus palabras. Ya sea que imagines un paisaje surrealista, un detallado boceto de personaje o un diseño abstracto único, nuestra herramienta genera imágenes de alta calidad en segundos. Simplemente introduce tu descripción, elige tu estilo artístico preferido, define la forma y decide cuántas variaciones quieres. La IA hará el resto. Nuestra IA para convertir texto en imagen está disponible a través de cualquier navegador web y es compatible con todos los dispositivos (PC, Mac, Android, iOS) sin necesidad de software adicional. Esta poderosa herramienta es ideal para artistas, diseñadores, creadores de contenido o cualquiera que quiera llevar sus conceptos creativos a la realidad visual.
                    ## ¿Por qué deberías usar la red neuronal generadora de imágenes a partir de texto?
                    El generador AI de texto a imagen abre una nueva dimensión en la creación de arte digital. Es una herramienta excelente para artistas que exploran nuevos estilos, mercadólogos que crean visuales atractivos y escritores que visualizan escenas o personajes. Además, es increíblemente fácil de usar y eficiente.
                </p>
           </div>
              <div class=" w-full flex flex-col items-center space-y-6">
               <h1 class=" text-black font-Inter text-[2rem] sm:text-[2.5rem] font-normal">Funciones del generador de texto a imagen:</h1>
              <div class="text-black font-Inter text-xl font-normal max-w-[59.0925rem]">
                    <p>
                        Entrada de texto personalizable: Describe en detalle lo que deseas y nuestra IA convertirá tus palabras en imágenes.
                        <br> Múltiples estilos artísticos: Elige entre una variedad de estilos, como anime pintado, pintura digital, cómic vintage, acuarela y muchos más.
                        <br> Selección de forma: Especifica la forma de la imagen, ya sea un amplio paisaje, un retrato alto o un cuadrado estándar.
                        <br> Control de cantidad: Determina cuántos resultados de imágenes deseas obtener de un solo pedido, obteniendo múltiples interpretaciones visuales de tu texto.
                        <br> Imágenes de alta calidad: Disfruta de imágenes de alta resolución creadas por nuestra IA avanzada, conservando la calidad y esencia de tu idea original.
                    </p>
                    <ul class="pl-8 list-disc">
                        <li>
                            Customizable Text Input: Describe what you want in detail, and our AI will interpret your words into images.
                        </li>
                        <li>
                            Multiple Art Styles: Choose from a variety of art styles like Painted Anime, Digital Painting, Vintage Comic, Watercolor, and more.
                        </li>
                        <li>
                            Shape Selection: Specify the shape of your image - whether it's a wide landscape, a tall portrait, or a standard square.
                        </li>
                        <li>
                            Quantity Control: Decide how many image results you want from a single prompt, giving you multiple visual interpretations of your text.
                        </li>
                        <li>
                            High-Quality Images: Enjoy high-resolution images generated by our advanced AI, retaining the quality and essence of your original idea.
                        </li>
                    </ul>

                    <p>
                        ¿Cómo generar imágenes a partir de texto? Paso 1: Visita Text-to-Image.ai en tu dispositivo.
                        Paso 2: Introduce tu texto descriptivo en el campo de entrada.
                        Paso 3: Selecciona tu estilo artístico deseado, la forma y la cantidad de resultados.
                        Paso 4: Haz clic en el botón "Generar".
                        Paso 5: Visualiza las imágenes creadas por la IA basadas en tu descripción. Elige y descarga tus favoritas directamente en tu dispositivo.
                        Con Text-to-Image.ai, puedes convertir cualquier concepto textual en arte visual impresionante. Actualizamos continuamente nuestra IA para ofrecerte la mejor y más innovadora experiencia. Comparte esta herramienta con amigos y familiares y comienza a crear hoy.
                        Nuestra herramienta respeta el proceso creativo y está diseñada para un uso ético. Consulta nuestros Términos de Servicio para obtener más detalles.
                    </p>
                </div>

           </div>
        </article>
    </section>
</template>